/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6 at Fri Sep 09 10:15:26 2016. */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _NodeMessage {
    pb_callback_t reading;
/* @@protoc_insertion_point(struct:NodeMessage) */
} NodeMessage;

typedef struct _SensorReading {
    bool has_id;
    uint32_t id;
    bool has_error;
    uint32_t error;
    bool has_value1;
    int32_t value1;
    bool has_value2;
    int32_t value2;
    bool has_value3;
    int32_t value3;
    bool has_value4;
    int32_t value4;
    bool has_value5;
    int32_t value5;
    bool has_value6;
    int64_t value6;
    bool has_value7;
    int64_t value7;
    bool has_value8;
    int64_t value8;
    bool has_value9;
    int64_t value9;
    bool has_value10;
    int64_t value10;
/* @@protoc_insertion_point(struct:SensorReading) */
} SensorReading;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SensorReading_init_default               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define NodeMessage_init_default                 {{{NULL}, NULL}}
#define SensorReading_init_zero                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define NodeMessage_init_zero                    {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define NodeMessage_reading_tag                  1
#define SensorReading_id_tag                     1
#define SensorReading_error_tag                  2
#define SensorReading_value1_tag                 3
#define SensorReading_value2_tag                 4
#define SensorReading_value3_tag                 5
#define SensorReading_value4_tag                 6
#define SensorReading_value5_tag                 7
#define SensorReading_value6_tag                 8
#define SensorReading_value7_tag                 9
#define SensorReading_value8_tag                 10
#define SensorReading_value9_tag                 11
#define SensorReading_value10_tag                12

/* Struct field encoding specification for nanopb */
extern const pb_field_t SensorReading_fields[13];
extern const pb_field_t NodeMessage_fields[2];

/* Maximum encoded size of messages (where known) */
#define SensorReading_size                       97
/* NodeMessage_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SENSOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
