<?php
/** @package Showcase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("Alarm_RegelMap.php");

/**
 * Alarm_RegelDAO provides object-oriented access to the alarm_regel table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Showcase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class Alarm_RegelDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Node;

	/** @var string */
	public $Sensor;

	/** @var string */
	public $AlarmTrigger;


	/**
	 * Returns a dataset of Alarm objects with matching AlarmRegel
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAlarms($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_qqgttvcq7u148nkqjhx2hsbdi", $criteria);
	}

	/**
	 * Returns a dataset of AlarmNotificatie objects with matching AlarmRegel
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAlarmNotificaties($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_alarm_notificatie_alarm_regel", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Node
	 * @return Node
	 */
	public function GetNode()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_4stgr2ch3nidujfk8pial5sdv");
	}

	/**
	 * Returns the foreign object based on the value of Sensor
	 * @return Sensor
	 */
	public function GetSensor()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_afhhe5d4s0if67l0h6fxmdj08");
	}


}
?>