<?php
/** @package Showcase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AlarmNotificatieMap.php");

/**
 * AlarmNotificatieDAO provides object-oriented access to the alarm_notificatie table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Showcase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AlarmNotificatieDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $AlarmRegel;

	/** @var string */
	public $Kanaal;

	/** @var string */
	public $P1;

	/** @var string */
	public $P2;

	/** @var string */
	public $P3;

	/** @var string */
	public $P4;

	/** @var string */
	public $Meldingtekst;


	/**
	 * Returns the foreign object based on the value of AlarmRegel
	 * @return AlarmRegel
	 */
	public function GetAlarmRegel()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_alarm_notificatie_alarm_regel");
	}


}
?>