<?php
/** @package Showcase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("Laatste_ObservatieMap.php");

/**
 * Laatste_ObservatieDAO provides object-oriented access to the laatste_observatie_per_node_sensor table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Showcase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class Laatste_ObservatieDAO extends Phreezable
{
	/** @var int */
	public $Observatieid;

	/** @var string */
	public $Node;

	/** @var string */
	public $Sensor;
	
	/** @var string */
	public $Sensoreenheid;

	/** @var string */
	public $Observatiewaarde;

	/** @var date */
	public $Observatiedatum;



}
?>