<?php
/** @package Showcase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("NodeMap.php");

/**
 * NodeDAO provides object-oriented access to the node table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Showcase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class NodeDAO extends Phreezable
{
	/** @var string */
	public $DevEui;

	/** @var int */
	public $Version;

	/** @var string */
	public $Omschrijving;


	/**
	 * Returns a dataset of NodeThreshold objects with matching NodeId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetNodeThresholds($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_4stgr2ch3nidujfk8pial5sdv", $criteria);
	}

	/**
	 * Returns a dataset of Observation objects with matching NodeId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetObservations($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_smi270lm0koqq55tj5bfisawt", $criteria);
	}


}
?>