<?php
/** @package Showcase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("NodeThresholdMap.php");

/**
 * NodeThresholdDAO provides object-oriented access to the node_threshold table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Showcase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class NodeThresholdDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Version;

	/** @var string */
	public $KeepaliveTimeout;

	/** @var string */
	public $NodeId;

	/** @var string */
	public $RmqChannel;

	/** @var string */
	public $SensorId;

	/** @var string */
	public $State;


	/**
	 * Returns a dataset of Alarm objects with matching NodeThresholdId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAlarms($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_qqgttvcq7u148nkqjhx2hsbdi", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of NodeId
	 * @return Node
	 */
	public function GetNode()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_4stgr2ch3nidujfk8pial5sdv");
	}

	/**
	 * Returns the foreign object based on the value of SensorId
	 * @return Sensor
	 */
	public function GetSensor()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_afhhe5d4s0if67l0h6fxmdj08");
	}


}
?>