<?php
/** @package Showcase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ObservatieMap.php");

/**
 * ObservatieDAO provides object-oriented access to the observatie table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Showcase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ObservatieDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Node;

	/** @var string */
	public $Sensor;

	/** @var date */
	public $DatumTijdAangemaakt;

	/** @var string */
	public $Waarde;


	/**
	 * Returns a dataset of Alarm objects with matching Observatie
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetAlarms($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_alarm_observatie", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Node
	 * @return Node
	 */
	public function GetNode()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_observatie_node");
	}

	/**
	 * Returns the foreign object based on the value of Sensor
	 * @return Sensor
	 */
	public function GetSensor()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_observatie_sensor");
	}


}
?>