<?php
/** @package Showcase::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("SensorMap.php");

/**
 * SensorDAO provides object-oriented access to the sensor table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Showcase::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class SensorDAO extends Phreezable
{
	/** @var string */
	public $SensorId;

	/** @var int */
	public $Version;

	/** @var string */
	public $Omschrijving;


	/**
	 * Returns a dataset of NodeThreshold objects with matching SensorId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetNodeThresholds($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_afhhe5d4s0if67l0h6fxmdj08", $criteria);
	}

	/**
	 * Returns a dataset of Observation objects with matching SensorId
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetObservations($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_3vtmlnui6re2o9jq4vqpa2t06", $criteria);
	}


}
?>