/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Fri Sep 09 10:15:26 2016. */

#include "sensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorReading_fields[13] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, SensorReading, id, id, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, SensorReading, error, id, 0),
    PB_FIELD(  3, SINT32  , OPTIONAL, STATIC  , OTHER, SensorReading, value1, error, 0),
    PB_FIELD(  4, SINT32  , OPTIONAL, STATIC  , OTHER, SensorReading, value2, value1, 0),
    PB_FIELD(  5, SINT32  , OPTIONAL, STATIC  , OTHER, SensorReading, value3, value2, 0),
    PB_FIELD(  6, SINT32  , OPTIONAL, STATIC  , OTHER, SensorReading, value4, value3, 0),
    PB_FIELD(  7, SINT32  , OPTIONAL, STATIC  , OTHER, SensorReading, value5, value4, 0),
    PB_FIELD(  8, SINT64  , OPTIONAL, STATIC  , OTHER, SensorReading, value6, value5, 0),
    PB_FIELD(  9, SINT64  , OPTIONAL, STATIC  , OTHER, SensorReading, value7, value6, 0),
    PB_FIELD( 10, SINT64  , OPTIONAL, STATIC  , OTHER, SensorReading, value8, value7, 0),
    PB_FIELD( 11, SINT64  , OPTIONAL, STATIC  , OTHER, SensorReading, value9, value8, 0),
    PB_FIELD( 12, SINT64  , OPTIONAL, STATIC  , OTHER, SensorReading, value10, value9, 0),
    PB_LAST_FIELD
};

const pb_field_t NodeMessage_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, NodeMessage, reading, reading, &SensorReading_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(NodeMessage, reading) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SensorReading_NodeMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(NodeMessage, reading) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SensorReading_NodeMessage)
#endif


/* @@protoc_insertion_point(eof) */
